DigiShop/DigiShop.UI.Web/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DigiShop.BLL;
using DigiShop.Models;
using DigiShop;

namespace DigiShop.UI.Web.Controllers
{
    public class ClienteController : Controller
    {
        private IClienteDados bll;

        public ClienteController()
        {
            bll = AppContainer.ObterClienteBLL(); 
        }

        public ActionResult Excluir(string id)
        {
            var cliente = bll.ObterPorId(id);
            return View(cliente);
        }

        [HttpPost]
        public ActionResult Excluir(string id, FormCollection form)
        {
            try
            {

                bll.Excluir(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                var cliente = bll.ObterPorId(id);
                return View(cliente);
            }
        }


        public ActionResult Alterar(string id)
        {
            var cliente = bll.ObterPorId(id);
            return View(cliente);
        }

        [HttpPost]
        public ActionResult Alterar(Cliente cliente)
        {
            try
            {

                bll.Alterar(cliente);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(cliente);
            }
        }

        public ActionResult Detalhes(string id)
        {
            var cliente = bll.ObterPorId(id);
            return View(cliente);
        }

        public ActionResult Incluir() 
        {
            var cli = new Cliente();
            return View(cli);
        }

        [HttpPost]

        public ActionResult Incluir(Cliente cliente)
        {
            try
            {
               
                bll.Incluir(cliente);
                return RedirectToAction("Index");
            }
            catch (Exception ex) 
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(cliente);
            }
 
        }
        public ActionResult Index()
        {
            
            var lista = bll.ObterTodos();
            return View(lista);
           
        }
    }
}

DigiShop/DigiShop.UI.Web/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DigiShop.BLL;
using DigiShop.Models;
using DigiShop.UI.Web.Models;

namespace DigiShop.UI.Web.Controllers
{
    public class PedidoController : Controller
    {
        [HttpPost]
        public ActionResult Incluir(PedidoViewModel pedido)
        {
                var bllProduto = AppContainer.ObterProdutoBLL();
                var bllCliente = AppContainer.ObterClienteBLL();

                pedido.Clientes = bllCliente.ObterTodos();
                pedido.Produtos = bllProduto.ObterTodos();
                pedido.FormasPagamento = Enum.GetNames(typeof(FormaPagamentoEnum)).ToList();

            if (Request.Form["incluirProduto"] == "Incluir")
            {
                var item = new PedidoViewModel.Item();
                item.ProdutoId = pedido.NovoItemProdutoId;
                item.Quantidade = pedido.NovoItemQuantidade;

                var produto=bllProduto.ObterPorId(item.ProdutoId);
                item.Valor = produto.Preco;
                item.ProdutoNome = produto.Nome;
                pedido.Items.Add(item);


            }
            else if (Request.Form["Gravar"] == "Gravar")
            {
                //var bll = AppContainer.ObterPedidoBLL();
            }

            return View(pedido);
        }
        
        public ActionResult Incluir()
        {

            var bllCliente = AppContainer.ObterClienteBLL();
            var bllProduto = AppContainer.ObterProdutoBLL();


            var pedido = new PedidoViewModel();
                pedido.Clientes = bllCliente.ObterTodos();    
                pedido.Produtos= bllProduto.ObterTodos();



                pedido.FormasPagamento = Enum.GetNames(typeof(FormaPagamentoEnum)).ToList();
            
            


            return View(pedido);
        }
    }
}

DigiShop/DigiShop.UI.Web/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using DigiShop.Models;

namespace DigiShop.UI.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private IProdutosDados bll;

        public ProdutoController()
        {
            bll = AppContainer.ObterProdutoBLL();
        }

        public ActionResult Excluir(string id)
        {
            var produto = bll.ObterPorId(id);
            return View(produto);
        }

        [HttpPost]
        public ActionResult Excluir(string id, FormCollection form)
        {
            try
            {

                bll.Excluir(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                var produto = bll.ObterPorId(id);
                return View(produto);
            }
        }


        public ActionResult Alterar(string id)
        {
            var produto = bll.ObterPorId(id);
            return View(produto);
        }

        [HttpPost]
        public ActionResult Alterar(Produto produto)
        {
            try
            {

                bll.Alterar(produto);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(produto);
            }
        }

        public ActionResult Detalhes(string id)
        {
            var produto = bll.ObterPorId(id);
            return View(produto);
        }

        public ActionResult Incluir()
        {
            var prod = new Produto();
            return View(prod);
        }

        [HttpPost]

        public ActionResult Incluir(Produto produto)
        {
            try
            {
                bll.Incluir(produto);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(produto);
            }
        }

                // GET: Produto
            public ActionResult Index()
        {
            var lista = bll.ObterTodos();
            return View(lista); 
        }
    }
}

DigiShop/DigiShop.UI.Web/Controllers/UsuarioController.cs
using DigiShop.UI.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DigiShop.UI.Web.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Login()
        {
           



            return View();
        }

        [HttpPost]

        public ActionResult Logout(LoginViewModel login)
        {
            var usuarioStore = new UserStore<IdentityUser>();
            var usuarioGerenciador = new UserManager<IdentityUser>(usuarioStore);

            var usuario = usuarioGerenciador.Find(login.Nome, login.Senha);
            if(usuario == null)
            {
                ModelState.AddModelError("", "Usuário ou senha inválida");
            }else
            {
                var gerenciadorDeAutenticacao = HttpContext.GetOwinContext().Authentication;
                var identidade = usuarioGerenciador.CreateIdentity(usuario, DefaultAuthenticationTypes.ApplicationCookie);
                gerenciadorDeAutenticacao.SignIn(new Microsoft.Owin.Security.AuthenticationProperties { }, identidade);
                Response.Redirect("~/");
            }

            return View(login);
        }

        public ActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registro(NovoUsuarioViewModel novo)
        {
            if (string.IsNullOrEmpty(novo.Nome))
            {
                ModelState.AddModelError("", "O nome deve ser informado");
            }

            if (!string.IsNullOrEmpty(novo.Senha) && (novo.Senha != novo.ConfirmarSenha))
            {
                ModelState.AddModelError("", "A senha deve ser igual a confirmação");
            }

            if(ModelState.IsValid)
            {
                var usuarioStore = new UserStore<IdentityUser>();
                var usuarioGerenciador = new UserManager<IdentityUser>(usuarioStore);
                var usuario = new IdentityUser() { UserName = novo.Nome };

                var resultado = usuarioGerenciador.Create(usuario, novo.Senha);
                if (resultado.Succeeded) 
                {
                    var gerenciadorDeAutenticacao = HttpContext.GetOwinContext().Authentication;
                    var identidadeUsuario = usuarioGerenciador.CreateIdentity(usuario, DefaultAuthenticationTypes.ApplicationCookie);
                    gerenciadorDeAutenticacao.SignIn(new Microsoft.Owin.Security.AuthenticationProperties() { }, identidadeUsuario);
                    Response.Redirect("~/");
                }
            }

            return View(novo);
        }
    }
}

DigiShop/DigiShop.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("DigiShop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar a navegação" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Produtos", "Index", "Produto", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pedidos", "Index", "Pedido", new { area = "" }, new { @class = "nav-link" })</li>
                    
                    
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        { 
                                @Html.ActionLink(User.Identity.Name + " - Logout","Logout", "Usuario", new { area = "" }, new { @class = "nav-link" })


                        }
                                else
                                {
                                    @Html.ActionLink("Login", "Login", "Usuario", new { area = "" }, new { @class = "nav-link" })
        

                            }


                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Loja DigiShop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>